/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.inventario.struts.form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cetia.sicaco.hibernate.CtaTcuTipoCuenta;
import com.cetia.sicaco.hibernate.CtrBanBanco;
import com.cetia.sicaco.hibernate.InvClaClasificadoId;
import com.cetia.sicaco.hibernate.InvPcbProveedorCuentaBancaria;
import com.cetia.sicaco.hibernate.InvPcbProveedorCuentaBancariaId;
import com.cetia.sicaco.hibernate.InvProProveedor;
import com.cetia.sicaco.struts.BasicForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-27-2008
 * 
 * XDoclet definition:
 * @struts.form name="prCuentaBancariaForm"
 */
public class PrCuentaBancariaForm extends BasicForm {
	/*
	 * Generated Methods
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -8838857920199922168L;
	
	private InvPcbProveedorCuentaBancaria proveedorCuentaBancariaH = new InvPcbProveedorCuentaBancaria();
	
	private int proId;
	private Integer idBan;
	private String cuenta;

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getAudFechaCreacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (proveedorCuentaBancariaH.getAudFechaCreacion()!=null)?(sdf.format(proveedorCuentaBancariaH.getAudFechaCreacion())):null;
	}

	public String getAudFechaModificacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (proveedorCuentaBancariaH.getAudUsuarioModificacion()!=null)?(sdf.format(proveedorCuentaBancariaH.getAudFechaModificacion())):null;
	}

	public String getAudUsuarioCreacion() {
		return proveedorCuentaBancariaH.getAudUsuarioCreacion();
	}

	public String getAudUsuarioModificacion() {
		return proveedorCuentaBancariaH.getAudUsuarioModificacion();
	}

	public InvPcbProveedorCuentaBancariaId getId() {
		if(proveedorCuentaBancariaH.getId() == null){
			proveedorCuentaBancariaH.setId(new InvPcbProveedorCuentaBancariaId());
		}
		return proveedorCuentaBancariaH.getId();
	}

	public void setAudFechaCreacion(Date audFechaCreacion) {
		proveedorCuentaBancariaH.setAudFechaCreacion(audFechaCreacion);
	}

	public void setAudFechaModificacion(Date audFechaModificacion) {
		proveedorCuentaBancariaH.setAudFechaModificacion(audFechaModificacion);
	}

	public void setAudFechaCreacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			proveedorCuentaBancariaH.setAudFechaCreacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}
	
	public void setAudFechaModificacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			proveedorCuentaBancariaH.setAudFechaModificacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}
	
	public void setAudUsuarioCreacion(String audUsuarioCreacion) {
		proveedorCuentaBancariaH.setAudUsuarioCreacion(audUsuarioCreacion);
	}

	public void setAudUsuarioModificacion(String audUsuarioModificacion) {
		proveedorCuentaBancariaH.setAudUsuarioModificacion(audUsuarioModificacion);
	}

	public void setId(InvPcbProveedorCuentaBancariaId id) {
		proveedorCuentaBancariaH.setId(id);
	}
	
	public void setBanId(Integer banId){
		if(proveedorCuentaBancariaH.getId() == null){
			proveedorCuentaBancariaH.setId(new InvPcbProveedorCuentaBancariaId());
		}
		InvPcbProveedorCuentaBancariaId id = new InvPcbProveedorCuentaBancariaId();
		CtrBanBanco banco = new CtrBanBanco();
		banco.setBanId(banId);
		id.setCtrBanBanco(banco);
		proveedorCuentaBancariaH.setId(id);
	}
	
	public Integer getBanId(){
		if(proveedorCuentaBancariaH.getId() == null){
			proveedorCuentaBancariaH.setId(new InvPcbProveedorCuentaBancariaId());
		}
		return proveedorCuentaBancariaH.getId().getCtrBanBanco().getBanId();
	}

	public CtaTcuTipoCuenta getCtaTcuTipoCuenta() {
		return proveedorCuentaBancariaH.getCtaTcuTipoCuenta();
	}

	public void setCtaTcuTipoCuenta(CtaTcuTipoCuenta ctaTcuTipoCuenta) {
		proveedorCuentaBancariaH.setCtaTcuTipoCuenta(ctaTcuTipoCuenta);
	}

	public InvPcbProveedorCuentaBancaria getProveedorCuentaBancariaH() {
		return proveedorCuentaBancariaH;
	}

	public void setProveedorCuentaBancariaH(
			InvPcbProveedorCuentaBancaria proveedorCuentaBancariaH) {
		this.proveedorCuentaBancariaH = proveedorCuentaBancariaH;
	}

	public int getProId() {
		return proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

	public Integer getIdBan() {
		return idBan;
	}

	public void setIdBan(Integer idBan) {
		this.idBan = idBan;
	}

	public String getCuenta() {
		return cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	
	public boolean isFillAuditoria() {
		// TODO Auto-generated method stub
		return true;
	}
}