/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.orden.struts.form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;

import com.cetia.sicaco.hibernate.InvProProveedor;
import com.cetia.sicaco.hibernate.OrdOcoOrdenDeCompra;
import com.cetia.sicaco.hibernate.OrdRefCuentaReferencia;
import com.cetia.sicaco.struts.BasicForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-02-2008
 * 
 * XDoclet definition:
 * @struts.form name="ordenCompraForm"
 */
public class OrdenCompraForm extends BasicForm {
	/*
	 * Generated Methods
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 6957813538827578523L;

	private OrdOcoOrdenDeCompra compraH = new OrdOcoOrdenDeCompra();

	private String nombreAsoc;
	private Double credito;
	private Integer ini;
	private int don;
	private int ocoId;
	private String dis;
	private String check;
	private Double pagado;
	private int[] posiciones;
	private double[] valores;
	private String cuentaRef;
	private String ascCodigo2;
	private String ascCodigo3;
	private String ascNombre;
	private String codigo;
	
	private String proCodigo;
	private String proNombre;
	private String proRegistro;
	private String proNit;
	private String prestamoId;
	
	private String dis2;
	private int restart;
	private int param;
	private int impreOreimpre;
	
	private Integer idOrden;
	private Integer regalo;
	
	private int imprimir;
	
	private int ascEmp;
	private Date fechaEmision;
	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getAudFechaCreacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (compraH.getAudFechaCreacion()!=null)?(sdf.format(compraH.getAudFechaCreacion())):null;
	}

	public String getAudFechaModificacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (compraH.getAudUsuarioModificacion()!=null)?(sdf.format(compraH.getAudFechaModificacion())):null;
	}

	public String getAudUsuarioCreacion() {
		return compraH.getAudUsuarioCreacion();
	}

	public String getAudUsuarioModificacion() {
		return compraH.getAudUsuarioModificacion();
	}
/*
	public OrdOcoOrdenDeCompraId getId() {
		return compraH.getId();
	}
*/
	public InvProProveedor getInvProProveedor() {
		return compraH.getInvProProveedor();
	}

	public Integer getOcoCodigo() {
		return compraH.getOcoCodigo();
	}

	public String getOcoElaborado() {
		return compraH.getOcoElaborado();
	}
/*
	public Date getOcoEmision() {
		return compraH.getOcoEmision();
	}
	*/
	public String getOcoEmision() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (compraH.getOcoEmision()!=null)?(sdf.format(compraH.getOcoEmision())):null;
	}

	public String getOcoEstado() {
		return compraH.getOcoEstado();
	}

	public Double getOcoMonto() {
		return compraH.getOcoMonto();
	}

	public Double getOcoPagado() {
		return compraH.getOcoPagado();
	}

	public Double getOcoSaldo() {
		return compraH.getOcoSaldo();
	}

	public String getOcoVencimiento() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (compraH.getOcoVencimiento()!=null)?(sdf.format(compraH.getOcoVencimiento())):null;
	}
/*
	public Set getOrdPagoCompras() {
		return compraH.getOrdPagoCompras();
	}
*/
	public OrdRefCuentaReferencia getOrdRefCuentaReferencia() {
		return compraH.getOrdRefCuentaReferencia();
	}

	public void setAudFechaCreacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			compraH.setAudFechaCreacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}
	
	public void setAudFechaModificacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			compraH.setAudFechaModificacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}
	
	public void setAudFechaCreacion(Date audFechaCreacion) {
		compraH.setAudFechaCreacion(audFechaCreacion);
	}

	public void setAudFechaModificacion(Date audFechaModificacion) {
		compraH.setAudFechaModificacion(audFechaModificacion);
	}

	public void setAudUsuarioCreacion(String audUsuarioCreacion) {
		compraH.setAudUsuarioCreacion(audUsuarioCreacion);
	}

	public void setAudUsuarioModificacion(String audUsuarioModificacion) {
		compraH.setAudUsuarioModificacion(audUsuarioModificacion);
	}
/*
	public void setId(OrdOcoOrdenDeCompraId id) {
		compraH.setId(id);
	}
*/
	public void setInvProProveedor(InvProProveedor invProProveedor) {
		compraH.setInvProProveedor(invProProveedor);
	}

	public void setOcoCodigo(Integer ocoCodigo) {
		compraH.setOcoCodigo(ocoCodigo);
	}

	public void setOcoElaborado(String ocoElaborado) {
		compraH.setOcoElaborado(ocoElaborado);
	}

	public void setOcoEmision(Date ocoEmision) {
		compraH.setOcoEmision(ocoEmision);
	}
	
	public void setOcoEmision(String ocoEmision) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			compraH.setOcoEmision(sdf.parse(ocoEmision));
		} catch (ParseException e) {
		}
	}

	public void setOcoEstado(String ocoEstado) {
		compraH.setOcoEstado(ocoEstado);
	}

	public void setOcoMonto(Double ocoMonto) {
		compraH.setOcoMonto(ocoMonto);
	}

	public void setOcoPagado(Double ocoPagado) {
		compraH.setOcoPagado(ocoPagado);
	}

	public void setOcoSaldo(Double ocoSaldo) {
		compraH.setOcoSaldo(ocoSaldo);
	}

	public void setOcoVencimiento(Date ocoVencimiento) {
		compraH.setOcoVencimiento(ocoVencimiento);
	}
	
	public void setOcoVencimiento(String ocoVencimiento) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			compraH.setOcoVencimiento(sdf.parse(ocoVencimiento));
		} catch (ParseException e) {
		}
	}
/*
	public void setOrdPagoCompras(Set ordPagoCompras) {
		compraH.setOrdPagoCompras(ordPagoCompras);
	}
*/
	public void setOrdRefCuentaReferencia(
			OrdRefCuentaReferencia ordRefCuentaReferencia) {
		compraH.setOrdRefCuentaReferencia(ordRefCuentaReferencia);
	}
	
	public String getAscCodigo2() {
		return ascCodigo2;
	}

	public void setAscCodigo2(String ascCodigo2) {
		this.ascCodigo2 = ascCodigo2;
	}

	public String getNombreAsoc() {
		return nombreAsoc;
	}

	public void setNombreAsoc(String nombreAsoc) {
		this.nombreAsoc = nombreAsoc;
	}

	public OrdOcoOrdenDeCompra getCompraH() {
		return compraH;
	}

	public void setCompraH(OrdOcoOrdenDeCompra compraH) {
		this.compraH = compraH;
	}

	public Double getCredito() {
		return credito;
	}

	public void setCredito(Double credito) {
		this.credito = credito;
	}

	public Integer getIni() {
		return ini;
	}

	public void setIni(Integer ini) {
		this.ini = ini;
	}

	public int getDon() {
		return don;
	}

	public void setDon(int don) {
		this.don = don;
	}

	public void setOcoId(int ocoId) {
		this.ocoId = ocoId;
	}

	public String getDis() {
		return dis;
	}

	public void setDis(String dis) {
		this.dis = dis;
	}

	public String getCheck() {
		return check;
	}

	public void setCheck(String check) {
		this.check = check;
	}

	public Double getPagado() {
		return pagado;
	}

	public void setPagado(Double pagado) {
		this.pagado = pagado;
	}

	public int[] getPosiciones() {
		return posiciones;
	}

	public void setPosiciones(int[] posiciones) {
		this.posiciones = posiciones;
	}

	public double[] getValores() {
		return valores;
	}

	public void setValores(double[] valores) {
		this.valores = valores;
	}

	public Integer getOcoDonacion() {
		return compraH.getOcoDonacion();
	}

	public Integer getOcoId() {
		return compraH.getOcoId();
	}

	public Set getOrdPcoPagoCompras() {
		return compraH.getOrdPcoPagoCompras();
	}

	public void setOcoDonacion(Integer ocoDonacion) {
		compraH.setOcoDonacion(ocoDonacion);
	}

	public void setOcoId(Integer ocoId) {
		compraH.setOcoId(ocoId);
	}

	public void setOrdPcoPagoCompras(Set ordPcoPagoCompras) {
		compraH.setOrdPcoPagoCompras(ordPcoPagoCompras);
	}

	public String getCliCodigo() {
		return compraH.getCliCodigo();
	}

	public void setCliCodigo(String cliCodigo) {
		compraH.setCliCodigo(cliCodigo);
	}

	public String getCuentaRef() {
		return cuentaRef;
	}

	public void setCuentaRef(String cuentaRef) {
		this.cuentaRef = cuentaRef;
	}

	public String getAscCodigo() {
		return compraH.getAscCodigo();
	}

	public void setAscCodigo(String ascCodigo) {
		compraH.setAscCodigo(ascCodigo);
	}

	public String getAscCodigo3() {
		return ascCodigo3;
	}

	public void setAscCodigo3(String ascCodigo3) {
		this.ascCodigo3 = ascCodigo3;
	}

	public String getAscNombre() {
		return ascNombre;
	}

	public void setAscNombre(String ascNombre) {
		this.ascNombre = ascNombre;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	
	public boolean isFillAuditoria() {
		// TODO Auto-generated method stub
		return true;
	}

	public String getProCodigo() {
		return proCodigo;
	}

	public void setProCodigo(String proCodigo) {
		this.proCodigo = proCodigo;
	}

	public String getProNombre() {
		return proNombre;
	}

	public void setProNombre(String proNombre) {
		this.proNombre = proNombre;
	}

	public String getProRegistro() {
		return proRegistro;
	}

	public void setProRegistro(String proRegistro) {
		this.proRegistro = proRegistro;
	}

	public String getProNit() {
		return proNit;
	}

	public void setProNit(String proNit) {
		this.proNit = proNit;
	}

	public String getPrestamoId() {
		return prestamoId;
	}

	public void setPrestamoId(String prestamoId) {
		this.prestamoId = prestamoId;
	}

	public String getDis2() {
		return dis2;
	}

	public void setDis2(String dis2) {
		this.dis2 = dis2;
	}

	public int getRestart() {
		return restart;
	}

	public void setRestart(int restart) {
		this.restart = restart;
	}

	public int getParam() {
		return param;
	}

	public void setParam(int param) {
		this.param = param;
	}

	public int getImpreOreimpre() {
		return impreOreimpre;
	}

	public void setImpreOreimpre(int impreOreimpre) {
		this.impreOreimpre = impreOreimpre;
	}

	public Integer getIdOrden() {
		return idOrden;
	}

	public void setIdOrden(Integer idOrden) {
		this.idOrden = idOrden;
	}

	public Integer getRegalo() {
		return regalo;
	}

	public void setRegalo(Integer regalo) {
		this.regalo = regalo;
	}

	public int getImprimir() {
		return imprimir;
	}

	public void setImprimir(int imprimir) {
		this.imprimir = imprimir;
	}

	public int getAscEmp() {
		return ascEmp;
	}

	public void setAscEmp(int ascEmp) {
		this.ascEmp = ascEmp;
	}
	
	public String getFechaEmision() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (this.fechaEmision!=null)?(sdf.format(this.fechaEmision)):null;
	}
	
	public Date getFEmision(){
		return this.fechaEmision;
	}
	
	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public void setFechaEmision(String fechaEmision) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			setFechaEmision(sdf.parse(fechaEmision));
		} catch (ParseException e) {
		}
	}

}