/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.control.struts.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.hibernate.Transaction;
import org.jmesa.facade.TableFacade;
import org.jmesa.facade.TableFacadeImpl;
import org.jmesa.limit.ExportType;
import org.jmesa.limit.Limit;
import org.jmesa.view.component.Column;
import org.jmesa.view.component.Row;
import org.jmesa.view.component.Table;
import org.jmesa.view.editor.BasicCellEditor;
import org.jmesa.view.editor.CellEditor;
import org.jmesa.view.html.HtmlBuilder;

import com.cetia.sicaco.control.struts.form.PaisForm;
import com.cetia.sicaco.hibernate.CtrEstEstadoDAO;
import com.cetia.sicaco.hibernate.CtrPaiPais;
import com.cetia.sicaco.hibernate.CtrPaiPaisDAO;
import com.cetia.sicaco.hibernate.CtrParParametrosDAO;
import com.cetia.sicaco.struts.Constantes;
import com.cetia.sicaco.struts.DMLAction;

/** 
 * MyEclipse Struts
 * Creation date: 09-18-2008
 * 
 * XDoclet definition:
 * @struts.action path="/pais" name="paisForm" input="redirectInvalidData" parameter="accion" scope="request" validate="true"
 * @struts.action-forward name="lista" path="pagina-lista.control.pais"
 */
public class PaisAction extends DMLAction {

	public String TABLA_ID = "ctrPaiPais";

	public ActionForward lista(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaisForm paisForm = (PaisForm)form;
		
		CtrPaiPaisDAO paisDAO = new CtrPaiPaisDAO(getSessionHibernate(request));		
		
		List lst = paisDAO.findAll();
		
		CtrEstEstadoDAO estadoDAO = new CtrEstEstadoDAO(getSessionHibernate(request));
		List estados = estadoDAO.findByTus("STD");
		request.setAttribute("listEstados", estados);

		TableFacade tableFacade = new TableFacadeImpl(TABLA_ID, request);
		tableFacade.setItems(lst);

		//---- Genera los tipos de formas con que se podran exportar los datos
		tableFacade.setExportTypes(response, ExportType.CSV, ExportType.JEXCEL);
		tableFacade.setStateAttr("restore");
		Limit limit = tableFacade.getLimit();
		if (limit.isExported()) {
			//---- exporta la tabla
			export(tableFacade);
			return null; 
		} else {
			//---- genera el html de la tabla para ser mostrada
			String html = html(tableFacade, request);
			request.setAttribute(Constantes.LISTA_KEY, html);
		}
		//----- Variables de configuracion
		request.setAttribute("form", paisForm);
		request.setAttribute("edit", 0);
		request.setAttribute(Constantes.ACCION_KEY, "/pais");
		return mapping.findForward("lista");
	}

	//---- metodo que genera el html de la tabla del jmesa
	private String html(final TableFacade tableFacade, final HttpServletRequest request) {
		tableFacade.setColumnProperties("paiNombre", "ctrEstEstado.estNombre", "paiId");
		Table table = tableFacade.getTable();
		//---- Titulo de la tabla
		table.setCaptionKey("tbl.pais.caption");

		Row row = table.getRow();
		Column nombreColumna = row.getColumn("paiNombre");
		nombreColumna.setTitleKey("tbl.pais.paiNombre");
		nombreColumna.getCellRenderer().setCellEditor(new CellEditor(){

			public Object getValue(Object item, String property, int rowcount) {
				Object value = new BasicCellEditor().getValue(item, property, rowcount);
				CtrPaiPais pais = (CtrPaiPais)item;
				
				HtmlBuilder html = new HtmlBuilder();
				String link = tableFacade.getWebContext().getContextPath();
				link += "/control/pais.do?accion=cargarDatos&paiId=" + pais.getPaiId();
				html.a().href(link).close();
				html.append(value);
				html.aEnd();				
				return html.toString();		
			}
		});

		nombreColumna = row.getColumn("ctrEstEstado.estNombre");
		nombreColumna.setTitleKey("tbl.pais.ctrEstEstado.estNombre");

		nombreColumna = row.getColumn("paiId");
		nombreColumna.setTitleKey("tbl.pais.acciones");
		nombreColumna.getCellRenderer().setCellEditor(new CellEditor(){

			public Object getValue(Object item, String property, int rowcount) {
				Object value = new BasicCellEditor().getValue(item, property, rowcount);
				CtrPaiPais pais = (CtrPaiPais)item;

				HtmlBuilder html = new HtmlBuilder();
				value = "eliminar";
				//String link = tableFacade.getWebContext().getContextPath();
				html.a().onclick("handlerDeleteButton("+ pais.getPaiId() + ");").append("class=\"linkEliminar\"").title(value.toString()).id("deleteButtonId").close();
				//html.append(value);
				html.aEnd();				
				return html.toString();		
			}

		});

		return tableFacade.render();
	}

	//---- metodo que genera los exports, el formato que tendran
	private void export(final TableFacade tableFacade) {
		tableFacade.setColumnProperties("paiNombre", "ctrEstEstado.estNombre");
		Table table = tableFacade.getTable();
		//---- Titulo de la tabla
		table.setCaptionKey("tbl.pais.caption");

		Row row = table.getRow();
		Column nombreColumna = row.getColumn("paiNombre");
		nombreColumna.setTitleKey("tbl.pais.paiNombre");

		nombreColumna = row.getColumn("ctrEstEstado.estNombre");
		nombreColumna.setTitleKey("tbl.pais.ctrEstEstado.estNombre");

		tableFacade.render();
	}

	public ActionForward guardar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaisForm paisForm = (PaisForm)form;
		
		CtrPaiPaisDAO paisDAO = new CtrPaiPaisDAO(getSessionHibernate(request));

		Transaction tx = paisDAO.getSession().beginTransaction();
		try{
			if(paisDAO.findByPaiNombre(paisForm.getPaisH().getPaiNombre()).isEmpty()){
				CtrParParametrosDAO parametrosDAO = new CtrParParametrosDAO(getSessionHibernate(request));
				
				CtrEstEstadoDAO estadoDAO = new CtrEstEstadoDAO(getSessionHibernate(request));
				paisForm.setCtrEstEstado(estadoDAO.findById(paisForm.getCtrEstEstado().getEstId()));
				paisDAO.save(paisForm.getPaisH());
			}else{
				mensajes("errors.pais.NombreRepetido",request);
				return lista(mapping, form, request, response);
			}
		}catch(Exception e){
			tx.rollback();
			e.printStackTrace();
		}finally{
			tx.commit();
			paisDAO.getSession().flush();
			paisDAO.getSession().clear();
			
		}
		return lista(mapping,new PaisForm(),request,response);
	} 

	public ActionForward cargarDatos(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaisForm paisForm = (PaisForm)form;
		
		CtrPaiPaisDAO paisDAO = new CtrPaiPaisDAO(getSessionHibernate(request));		
		paisForm.setPaisH(paisDAO.findById(paisForm.getPaiId()));
		
		List lst = paisDAO.findAll();
		
		CtrEstEstadoDAO estadoDAO = new CtrEstEstadoDAO(getSessionHibernate(request));
		List estados = estadoDAO.findByTus("STD");
		request.setAttribute("listEstados", estados);

		TableFacade tableFacade = new TableFacadeImpl(TABLA_ID, request);
		tableFacade.setItems(lst);

		//---- Genera los tipos de formas con que se podran exportar los datos
		tableFacade.setExportTypes(response, ExportType.CSV, ExportType.JEXCEL);
		tableFacade.setStateAttr("restore");
		Limit limit = tableFacade.getLimit();
		if (limit.isExported()) {
			//---- exporta la tabla
			export(tableFacade);
			return null; 
		} else {
			//---- genera el html de la tabla para ser mostrada
			String html = html(tableFacade, request);
			request.setAttribute(Constantes.LISTA_KEY, html);
		}
		//----- Variables de configuracion
		request.setAttribute("form", paisForm);
		request.setAttribute("edit", 1);
		request.setAttribute(Constantes.ACCION_KEY, "/pais");
		return mapping.findForward("lista");
	}


	public ActionForward redirectInvalidData(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		ActionErrors errors = (ActionErrors)request.getSession().getAttribute(Constantes.ERRORS);
		saveMessages(request, errors);
		return lista(mapping, form, request, response);
	}

	public void mensajes(String msg, HttpServletRequest request){
		ActionErrors errors = new ActionErrors();
		errors.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage(msg));
		saveMessages(request, errors);
	}
	
	public ActionForward eliminar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaisForm paisForm = (PaisForm)form;
		
		CtrPaiPaisDAO paisDAO = new CtrPaiPaisDAO(getSessionHibernate(request));

		Transaction tx = paisDAO.getSession().beginTransaction();
		try{
			CtrPaiPais pais = paisDAO.findById(paisForm.getPaiId2());
			if(pais.getInvProProveedors().size() > 0 || pais.getInvBodBodegases().size() > 0){
				mensajes("errors.pais.tieneHijos",request);
				return lista(mapping, form, request, response);
			}else{
				paisDAO.delete(pais);
			}
		}catch(Exception e){
			tx.rollback();
			e.printStackTrace();
		}finally{
			tx.commit();
			paisDAO.getSession().flush();
			paisDAO.getSession().clear();
			
		}
		mensajes("msg.eliminacionExitosa", request);
		return lista(mapping,new PaisForm(),request,response);
	} 
	
	public ActionForward salvar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaisForm paisForm = (PaisForm)form;
		
		CtrPaiPaisDAO paisDAO = new CtrPaiPaisDAO(getSessionHibernate(request));

		Transaction tx = paisDAO.getSession().beginTransaction();
		try{
			//if(paisDAO.findByPaiNombre(paisForm.getPaisH().getPaiNombre()).isEmpty()){
				CtrEstEstadoDAO estadoDAO = new CtrEstEstadoDAO(getSessionHibernate(request));
				paisForm.setCtrEstEstado(estadoDAO.findById(paisForm.getCtrEstEstado().getEstId()));
				paisDAO.merge(paisForm.getPaisH());
			/*}else{
				mensajes("errors.pais.NombreRepetido",request);
				return lista(mapping, form, request, response);
			}*/
		}catch(Exception e){
			tx.rollback();
			e.printStackTrace();
		}finally{
			tx.commit();
			paisDAO.getSession().flush();
			paisDAO.getSession().clear();
			
		}
		return lista(mapping,new PaisForm(),request,response);
	} 
	
	public ActionForward cancelar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		return lista(mapping, form, request, response);
	}

	
	protected Map getKeyMethodMap() {
		// TODO Auto-generated method stub
		HashMap<String, String> map = new HashMap<String, String>();
		map.put("cmd.pais.lista", "lista");
		map.put("cmd.pais.guardar", "guardar");
		map.put("cmd.pais.redirectInvalidData", "redirectInvalidData");
		map.put("cmd.pais.cargarDatos", "cargarDatos");
		map.put("cmd.pais.eliminar", "eliminar");
		map.put("cmd.pais.salvar", "salvar");
		map.put("cmd.pais.cancelar", "cancelar");
		return map;
	}
}