/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.inventario.struts.form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cetia.sicaco.hibernate.InvTclTipoClasificacion;
import com.cetia.sicaco.struts.BasicForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-25-2008
 * 
 * XDoclet definition:
 * @struts.form name="tipoClasificacionForm"
 */
public class TipoClasificacionForm extends BasicForm {
	/*
	 * Generated Methods
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -8493624106919279167L;
	
	private InvTclTipoClasificacion tipoClasificacionH = new InvTclTipoClasificacion();
	
	private String tclId;

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getAudFechaCreacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (tipoClasificacionH.getAudFechaCreacion()!=null)?(sdf.format(tipoClasificacionH.getAudFechaCreacion())):null;
	}

	public String getAudFechaModificacion() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		return (tipoClasificacionH.getAudUsuarioModificacion()!=null)?(sdf.format(tipoClasificacionH.getAudFechaModificacion())):null;
	}

	public String getAudUsuarioCreacion() {
		return tipoClasificacionH.getAudUsuarioCreacion();
	}

	public String getAudUsuarioModificacion() {
		return tipoClasificacionH.getAudUsuarioModificacion();
	}

	public Set getInvClaClasificados() {
		return tipoClasificacionH.getInvClaClasificados();
	}

	public String getTclClasificacion() {
		return tipoClasificacionH.getTclClasificacion();
	}

	public String getTclDescripcion() {
		return tipoClasificacionH.getTclDescripcion();
	}

	public void setAudFechaCreacion(Date audFechaCreacion) {
		tipoClasificacionH.setAudFechaCreacion(audFechaCreacion);
	}

	public void setAudFechaModificacion(Date audFechaModificacion) {
		tipoClasificacionH.setAudFechaModificacion(audFechaModificacion);
	}
	
	public void setAudFechaCreacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			tipoClasificacionH.setAudFechaCreacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}
	
	public void setAudFechaModificacion(String adufecString) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		try {
			tipoClasificacionH.setAudFechaModificacion(sdf.parse(adufecString));
		} catch (ParseException e) {
		}
	}

	public void setAudUsuarioCreacion(String audUsuarioCreacion) {
		tipoClasificacionH.setAudUsuarioCreacion(audUsuarioCreacion);
	}

	public void setAudUsuarioModificacion(String audUsuarioModificacion) {
		tipoClasificacionH.setAudUsuarioModificacion(audUsuarioModificacion);
	}

	public void setInvClaClasificados(Set invClaClasificados) {
		tipoClasificacionH.setInvClaClasificados(invClaClasificados);
	}

	public void setTclClasificacion(String tclClasificacion) {
		tipoClasificacionH.setTclClasificacion(tclClasificacion);
	}

	public void setTclDescripcion(String tclDescripcion) {
		tipoClasificacionH.setTclDescripcion(tclDescripcion);
	}

	public InvTclTipoClasificacion getTipoClasificacionH() {
		return tipoClasificacionH;
	}

	public void setTipoClasificacionH(InvTclTipoClasificacion tipoClasificacionH) {
		this.tipoClasificacionH = tipoClasificacionH;
	}

	public String getTclId() {
		return tclId;
	}

	public void setTclId(String tclId) {
		this.tclId = tclId;
	}

	
	public boolean isFillAuditoria() {
		// TODO Auto-generated method stub
		return true;
	}
}