/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.seguridad.struts.form;

import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cetia.sicaco.hibernate.SecSucSucursal;
import com.cetia.sicaco.struts.BasicForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-14-2008
 * 
 * XDoclet definition:
 * @struts.form name="sucursalForm"
 */
public class SucursalForm extends BasicForm {
	/*
	 * Generated Methods
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -8403567351264888758L;
	
	private SecSucSucursal sucursalH = new SecSucSucursal();


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Set getSecPerPersonas() {
		return sucursalH.getSecPerPersonas();
	}

	public String getSucDireccion() {
		return sucursalH.getSucDireccion();
	}

	public Integer getSucId() {
		return sucursalH.getSucId();
	}

	public String getSucNombre() {
		return sucursalH.getSucNombre();
	}

	public void setSecPerPersonas(Set secPerPersonas) {
		sucursalH.setSecPerPersonas(secPerPersonas);
	}

	public void setSucDireccion(String sucDireccion) {
		sucursalH.setSucDireccion(sucDireccion);
	}

	public void setSucId(Integer sucId) {
		sucursalH.setSucId(sucId);
	}

	public void setSucNombre(String sucNombre) {
		sucursalH.setSucNombre(sucNombre);
	}

	public SecSucSucursal getSucursalH() {
		return sucursalH;
	}

	public void setSucursalH(SecSucSucursal sucursalH) {
		this.sucursalH = sucursalH;
	}

	
	public boolean isFillAuditoria() {
		// TODO Auto-generated method stub
		return false;
	}
}