/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.cuentaCorriente.struts.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.hibernate.Transaction;
import org.jmesa.facade.TableFacade;
import org.jmesa.facade.TableFacadeImpl;
import org.jmesa.limit.ExportType;
import org.jmesa.limit.Limit;
import org.jmesa.view.component.Column;
import org.jmesa.view.component.Row;
import org.jmesa.view.component.Table;
import org.jmesa.view.editor.BasicCellEditor;
import org.jmesa.view.editor.CellEditor;
import org.jmesa.view.editor.DateCellEditor;
import org.jmesa.view.html.HtmlBuilder;

import com.cetia.sicaco.cuentaCorriente.struts.form.LineaAhorroForm;
import com.cetia.sicaco.hibernate.CtaLahLineaAhorro;
import com.cetia.sicaco.hibernate.CtaLahLineaAhorroDAO;
import com.cetia.sicaco.struts.Constantes;
import com.cetia.sicaco.struts.DMLAction;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2008
 * 
 * XDoclet definition:
 * @struts.action path="/lineaAhorro" name="lineaAhorroForm" input="com.cetia.sicaco.cuentaCorriente.struts.form.LineaAhorroForm" parameter="accion" scope="request" validate="true"
 * @struts.action-forward name="lista" path="pendiente"
 * @struts.action-forward name="redirectInvalidData" path="redirectInvalidData" redirect="true"
 */
public class LineaAhorroAction extends DMLAction {

	
	
	public String TABLA_ID = "ctaLahLineaAhorro";
	public ActionForward lista(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LineaAhorroForm lineaAhorroForm = (LineaAhorroForm) form;
		CtaLahLineaAhorroDAO ctaLahLineaAhorroDAO = new CtaLahLineaAhorroDAO(getSessionHibernate(request));
		List lst = ctaLahLineaAhorroDAO.findAll();
		TableFacade tableFacade = new TableFacadeImpl(TABLA_ID, request);
		tableFacade.setItems(lst);
		
		//---- Genera los tipos de formas con que se podran exportar los datos
		tableFacade.setExportTypes(response, ExportType.CSV, ExportType.JEXCEL);
		tableFacade.setStateAttr("restore");
		Limit limit = tableFacade.getLimit();
		if (limit.isExported()) {
        	//---- exporta la tabla
            export(tableFacade);
            return null; 
        } else {
        	//---- genera el html de la tabla para ser mostrada
            String html = html(tableFacade, request);
            request.setAttribute(Constantes.LISTA_KEY, html);
        }
        //----- Variables de configuracion
		request.setAttribute("form", lineaAhorroForm);
		request.setAttribute(Constantes.ACCION_KEY, "/lineaAhorro");
		return mapping.findForward("lista");
	}
	
	//---- metodo que genera el html de la tabla del jmesa
	private String html(final TableFacade tableFacade, final HttpServletRequest request) {
		tableFacade.setColumnProperties("lahNombre", "lahDescripcion","lahDesde","lahHasta","lahId");
		Table table = tableFacade.getTable();
		//---- Titulo de la tabla
		table.setCaptionKey("tbl.lah.caption");
		
		Row row = table.getRow();
		Column nombreColumna = row.getColumn("lahNombre");
		nombreColumna.setTitleKey("tbl.lah.lahNombre");
		
		nombreColumna = row.getColumn("lahDescripcion");
		nombreColumna.setTitleKey("tbl.lah.lahDescripcion");
		
		nombreColumna = row.getColumn("lahDesde");
		nombreColumna.setTitleKey("tbl.lah.lahDesde");
		nombreColumna.getCellRenderer().setCellEditor(new DateCellEditor("dd-MMM-yyyy"));
		
		nombreColumna = row.getColumn("lahHasta");
		nombreColumna.setTitleKey("tbl.lah.lahHasta");
		nombreColumna.getCellRenderer().setCellEditor(new DateCellEditor("dd-MMM-yyyy"));
		
		nombreColumna = row.getColumn("lahId");
		nombreColumna.setTitleKey("tbl.lah.acciones");
		nombreColumna.getCellRenderer().setCellEditor(new CellEditor(){

			public Object getValue(Object item, String property, int rowcount) {
				Object value = new BasicCellEditor().getValue(item, property, rowcount);
				CtaLahLineaAhorro lineaAhorro = (CtaLahLineaAhorro)item;
				HtmlBuilder html = new HtmlBuilder();
				value = "Editar";
				String link = tableFacade.getWebContext().getContextPath();
				link += "/cuentaCorriente/lineaAhorro.do?lahId="+lineaAhorro.getLahId()+"&lahNombre="
				+lineaAhorro.getLahNombre()+"&lahDescripcion="+ lineaAhorro.getLahDescripcion()+
				"&lahDesde="+lineaAhorro.getLahDesde()+"&lahHasta="+lineaAhorro.getLahHasta()+
				"&accion=cargarDatos&mdf=true";
				html.a().href().quote().append(link).quote().append("class=\"linkEditar\"").title(value.toString()).close();
			/*	html.a().href().quote().append(link).quote().close();
				html.append(value);*/
				html.aEnd();				
				return html.toString();		
			}
		});
		
		return tableFacade.render();
	}
	
	//---- metodo que genera los exports, el formato que tendran
	 private void export(final TableFacade tableFacade) {
		 tableFacade.setColumnProperties("lahNombre", "lahDescripcion","lahDesde","lahHasta","lahId");
			Table table = tableFacade.getTable();;
					
			//---- Titulo de la tabla
			table.setCaptionKey("tbl.lah.caption");
			
			Row row = table.getRow();
			Column nombreColumna = row.getColumn("lahNombre");
			nombreColumna.setTitleKey("tbl.lah.lahNombre");
			
			nombreColumna = row.getColumn("lahDescripcion");
			nombreColumna.setTitleKey("tbl.lah.lahDescripcion");
			
			nombreColumna = row.getColumn("lahDesde");
			nombreColumna.setTitleKey("tbl.lah.lahDesde");
			nombreColumna.getCellRenderer().setCellEditor(new DateCellEditor("dd-MMM-yyyy"));
			
			nombreColumna = row.getColumn("lahHasta");
			nombreColumna.setTitleKey("tbl.lah.lahHasta");
			nombreColumna.getCellRenderer().setCellEditor(new DateCellEditor("dd-MMM-yyyy"));
			
		tableFacade.render();
	}
	
	 public ActionForward guardar(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) {
			LineaAhorroForm lineaAhorroForm = (LineaAhorroForm)form;
			CtaLahLineaAhorroDAO lineaAhorroDAO = new CtaLahLineaAhorroDAO(getSessionHibernate(request));
			Transaction tx = lineaAhorroDAO.getSession().beginTransaction();
			try{
				if(!lineaAhorroForm.isMdf()){//ingresando un nuevo registro
					if(lineaAhorroDAO.findByLahNombre(lineaAhorroForm.getCtaLahLineaAhorroH().getLahNombre()).isEmpty()){
						lineaAhorroForm.getCtaLahLineaAhorroH().setLahId(lineaAhorroDAO.nextId());
						lineaAhorroDAO.save(lineaAhorroForm.getCtaLahLineaAhorroH());
					}else{
						mensajes("errors.lahNombreRepetido",request);
						return lista(mapping, form, request, response);
					}
				}else{//modificando un registro
					if(lineaAhorroDAO.findByUpdatedName(lineaAhorroForm.getLahId(),lineaAhorroForm.getLahNombre()).isEmpty()){
						lineaAhorroDAO.merge(lineaAhorroForm.getCtaLahLineaAhorroH());
					}else{
						mensajes("errors.lahNombreRepetido",request);
						return lista(mapping, form, request, response);
					}
				}
				tx.commit();
			}catch(Exception e){
				tx.rollback();
				e.printStackTrace();
			}finally{
				lineaAhorroDAO.getSession().flush();
				lineaAhorroDAO.getSession().clear();
				
			}
			return lista(mapping,new LineaAhorroForm(),request,response);
		} 
	 
	 public ActionForward cargarDatos(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) {
		 return lista(mapping, form, request, response);
	 }
	 
		public ActionForward redirectInvalidData(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response){
			ActionErrors errors = (ActionErrors)request.getSession().getAttribute(Constantes.ERRORS);
			saveMessages(request, errors);
			return lista(mapping, form, request, response);
		}
		
		public void mensajes(String msg, HttpServletRequest request){
			ActionErrors errors = new ActionErrors();
	        errors.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage(msg));
	        saveMessages(request, errors);
		}
	
	//*****************************/
	
	protected Map getKeyMethodMap() {
		// TODO Auto-generated method stub
		HashMap<String, String> map = new HashMap<String, String>();
		map.put("cmd.lah.lista", "lista");
		map.put("cmd.lah.guardar", "guardar");
		map.put("cmd.lah.cargarDatos", "cargarDatos");
		map.put("cmd.lah.redirectInvalidData", "redirectInvalidData");
		return map;
	}
}