/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cetia.sicaco.cuentaCorriente.struts.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.hibernate.Transaction;
import org.jmesa.facade.TableFacade;
import org.jmesa.facade.TableFacadeImpl;
import org.jmesa.limit.ExportType;
import org.jmesa.limit.Limit;
import org.jmesa.view.component.Column;
import org.jmesa.view.component.Row;
import org.jmesa.view.component.Table;
import org.jmesa.view.editor.BasicCellEditor;
import org.jmesa.view.editor.CellEditor;
import org.jmesa.view.html.HtmlBuilder;

import com.cetia.sicaco.cuentaCorriente.struts.form.PlanMesForm;
import com.cetia.sicaco.hibernate.CtaPlmPlanMeses;
import com.cetia.sicaco.hibernate.CtaPlmPlanMesesDAO;
import com.cetia.sicaco.struts.Constantes;
import com.cetia.sicaco.struts.DMLAction;
/** 
 * MyEclipse Struts
 * Creation date: 08-07-2008
 * 
 * XDoclet definition:
 * @struts.action path="/planMes" name="planMesForm" input="redirectInvalidData" parameter="accion" scope="request" validate="true"
 * @struts.action-forward name="lista" path="pagina-lista.cuentaCorriente.planMes"
 * @struts.action-forward name="redirectInvalidData" path="/planMes.do?accion=redirectInvalidData" redirect="true"
 */
public class PlanMesAction extends DMLAction {

	public String TABLA_ID = "ctaPlmPlanMeses";
	public ActionForward lista(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PlanMesForm planMesForm = (PlanMesForm) form;
		CtaPlmPlanMesesDAO ctaPlmPlanMesesDAO = new CtaPlmPlanMesesDAO(getSessionHibernate(request));
		List lst = ctaPlmPlanMesesDAO.findAll();
		TableFacade tableFacade = new TableFacadeImpl(TABLA_ID, request);
		tableFacade.setItems(lst);
		
		//---- Genera los tipos de formas con que se podran exportar los datos
		tableFacade.setExportTypes(response, ExportType.CSV, ExportType.JEXCEL);
		tableFacade.setStateAttr("restore");
		Limit limit = tableFacade.getLimit();
		if (limit.isExported()) {
        	//---- exporta la tabla
            export(tableFacade);
            return null; 
        } else {
        	//---- genera el html de la tabla para ser mostrada
            String html = html(tableFacade, request);
            request.setAttribute(Constantes.LISTA_KEY, html);
        }
        //----- Variables de configuracion
		request.setAttribute("form", planMesForm);
		request.setAttribute(Constantes.ACCION_KEY, "/planMes");
		return mapping.findForward("lista");
	}
	
	//---- metodo que genera el html de la tabla del jmesa
	private String html(final TableFacade tableFacade, final HttpServletRequest request) {
		tableFacade.setColumnProperties("plmNombre", "plmDescripcion","plmDuracion","plmId");
		Table table = tableFacade.getTable();
		//---- Titulo de la tabla
		table.setCaptionKey("tbl.plm.caption");
		
		Row row = table.getRow();
		Column nombreColumna = row.getColumn("plmNombre");
		nombreColumna.setTitleKey("tbl.plm.plmNombre");
		
		nombreColumna = row.getColumn("plmDescripcion");
		nombreColumna.setTitleKey("tbl.plm.plmDescripcion");
		
		nombreColumna = row.getColumn("plmDuracion");
		nombreColumna.setTitleKey("tbl.plm.plmDuracion");
		
		nombreColumna = row.getColumn("plmId");
		nombreColumna.setTitleKey("tbl.plm.acciones");
		nombreColumna.getCellRenderer().setCellEditor(new CellEditor(){

			public Object getValue(Object item, String property, int rowcount) {
				Object value = new BasicCellEditor().getValue(item, property, rowcount);
				CtaPlmPlanMeses planMeses = (CtaPlmPlanMeses)item;
				HtmlBuilder html = new HtmlBuilder();
				value = "Modificar";
				String link = tableFacade.getWebContext().getContextPath();
				link += "/cuentaCorriente/planMes.do?plmId="+planMeses.getPlmId()+"&plmNombre="
				+planMeses.getPlmNombre()+"&plmDescripcion="+ planMeses.getPlmDescripcion()+
				"&plmDuracion="+planMeses.getPlmDuracion()+"&accion=cargarDatos&mdf=true";
				html.a().href().quote().append(link).quote().append("class=\"linkEditar\"").title(value.toString()).close();
			/*	html.a().href().quote().append(link).quote().close();
				html.append(value);*/
				html.aEnd();				
				return html.toString();		
			}
		});
		
		return tableFacade.render();
	}
	
	//---- metodo que genera los exports, el formato que tendran
	 private void export(final TableFacade tableFacade) {
		 tableFacade.setColumnProperties("plmNombre", "plmDescripcion","plmDuracion");
			Table table = tableFacade.getTable();;
					
			//---- Titulo de la tabla
			table.setCaptionKey("tbl.plm.caption");
			
			Row row = table.getRow();
			Column nombreColumna = row.getColumn("plmNombre");
			nombreColumna.setTitleKey("tbl.plm.plmNombre");
			
			nombreColumna = row.getColumn("plmDescripcion");
			nombreColumna.setTitleKey("tbl.plm.plmDescripcion");
			
			nombreColumna = row.getColumn("plmDuracion");
			nombreColumna.setTitleKey("tbl.plm.plmDuracion");
			
		tableFacade.render();
	}
	
	 public ActionForward guardar(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) {
			PlanMesForm planMesForm = (PlanMesForm)form;
			CtaPlmPlanMesesDAO planMesesDAO = new CtaPlmPlanMesesDAO(getSessionHibernate(request));
			Transaction tx = planMesesDAO.getSession().beginTransaction();
			try{
				if(!planMesForm.isMdf()){//ingresando un nuevo registro
					if(planMesesDAO.findByPlmNombre(planMesForm.getCtaPlmPlanMesesH().getPlmNombre()).isEmpty()){
						planMesForm.getCtaPlmPlanMesesH().setPlmId(planMesesDAO.nextId());
						planMesesDAO.save(planMesForm.getCtaPlmPlanMesesH());
					}else{
						mensajes("errors.plmNombreRepetido",request);
						return lista(mapping, form, request, response);
					}
				}else{//modificando un registro
					if(planMesesDAO.findByUpdatedName(planMesForm.getPlmId(),planMesForm.getPlmNombre()).isEmpty()){
						planMesesDAO.merge(planMesForm.getCtaPlmPlanMesesH());
					}else{
						mensajes("errors.plmNombreRepetido",request);
						return lista(mapping, form, request, response);
					}
				}
				tx.commit();
			}catch(Exception e){
				tx.rollback();
				e.printStackTrace();
			}finally{
				planMesesDAO.getSession().flush();
				planMesesDAO.getSession().clear();
				
			}
			return lista(mapping,new PlanMesForm(),request,response);
		} 
	 
	 public ActionForward cargarDatos(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) {
		 return lista(mapping, form, request, response);
	 }
	 
		public ActionForward redirectInvalidData(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response){
			ActionErrors errors = (ActionErrors)request.getSession().getAttribute(Constantes.ERRORS);
			saveMessages(request, errors);
			return lista(mapping, form, request, response);
		}
		
		public void mensajes(String msg, HttpServletRequest request){
			ActionErrors errors = new ActionErrors();
	        errors.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage(msg));
	        saveMessages(request, errors);
		}
	
	//*****************************/
	
	protected Map getKeyMethodMap() {
		// TODO Auto-generated method stub
		HashMap<String, String> map = new HashMap<String, String>();
		map.put("cmd.plm.lista", "lista");
		map.put("cmd.plm.guardar", "guardar");
		map.put("cmd.plm.cargarDatos", "cargarDatos");
		map.put("cmd.plm.redirectInvalidData", "redirectInvalidData");
		return map;
	}
}